### PR TITLE
Added ValueAtPercentiles() as an optimization to multiple calls to ValueAtPercentile()

### PR DESCRIPTION
**Pull request by filipecosta90**
When doing an percentile analysis we normally require more than one percentile to be calculated for the given histogram. 
When that is the case `ValueAtPercentiles()` will deeply optimize the total time to retrieve the percentiles vs the other option which is multiple calls to `ValueAtQuantile()`.

To demonstrate it, I've added a benchmark that calculates p50, p95, p99, and p999 ( very common percentiles ) using `ValueAtPercentiles()` vs multiple calls to `ValueAtQuantile()` we see that the speedup factor is linear ( as expected given we reuse the work up until the previous quantile calculation! ).

```
$ make benchmark
GO111MODULE=on go get -t -v ./...
GO111MODULE=on go test -bench=. -benchmem
goos: linux
goarch: amd64
pkg: github.com/HdrHistogram/hdrhistogram-go
(...)
BenchmarkHistogramValueAtPercentileGivenPercentileSlice-8           1456            835252 ns/op               0 B/op          0 allocs/op
BenchmarkHistogramValueAtPercentilesGivenPercentileSlice-8          4633            226868 ns/op              64 B/op          2 allocs/op
(...)
```

NOTE: The `ValueAtPercentiles` optimization implies that you pass an ORDERED (smaller to greater) slice of percentiles

### CODE REVIEW

**Comment by giltene** [comment]
The new multi-perecentile api makes sense, and we should probabky consider a similar thing in the other language implementations.
However, a stylistic API comment: the current go implementation uses quantiles rather than percentiles, and for consistency, the plural version should probably be ValurAtQuantiles. The need or usefulness of a way to get plural quintiles efficiently is orthogonal to the choice between quantiles and percentiles.
I would suggest adding percentiles (in addition to quantiles) to the api as a separate concern. The pro/con arguments there will be interesting. Probably centering in convenience for percentile users on one side and annoying redundancy in the api on the other. I have so far avoided adding quantile methods to the java implementation, but have considered it, and am not sure which is the better choice. The argument fur adding percentiles to the go implementation is probably stringer because the other implementations have percentiles...

**Comment by filipecosta90** [comment]
> However, a stylistic API comment: the current go implementation uses quantiles rather than percentiles, and for consistency, the plural version should probably be ValurAtQuantiles. 

@giltene fixed it in the latest commit. 

With regards to the added tests/benchmarks, and to benchmark with a data distribution that makes sense I've added gonum as a test dependency. That raised the issue of testing with EOLife versions. If you guys agree I've kept only go 1.14 and go1.15 as the tested versions given all others have EOL. wdyt @giltene and @ahothan ?

**Comment by ahothan** [comment]
regarding naming, I also prefer a more consistent naming across languages. Python uses "percentile" and already has a bulk api that is indeed more optimized:

   
```
    def get_value_at_percentile(self, percentile):
        '''Get the value for a given percentile

        Args:
            percentile: a float in [0.0..100.0]
        Returns:
            the value for the given percentile
        '''

    def get_percentile_to_value_dict(self, percentile_list):
        '''A faster alternative to query values for a list of percentiles.

        Args:
            percentile_list: a list of percentiles in any order, dups will be ignored
            each element in the list must be a float value in [0.0 .. 100.0]
        Returns:
            a dict of percentile values indexed by the percentile

```

Although the distinction between "percentile" and "quantile" is not always clear cut, I think "percentile" is more accurate term because "quantile" is a more generic term and the api clearly cannot take anything else than percentiles (e.g. quartiles and such).
Perhaps we should leave the exiting quantile api and add 2 extra apis that use "percentile".

As for the signature of the new go api, I find it a bit annoying to use array indexing to access the percentile values as you need to remember to which index each percentile corresponds.
Python simply returns a dict of percentile values indexed by the percentile:
```
def test_perc_value_list():
    histogram = load_histogram()
    res = {90: 1000, 99.999: 100007935}
    assert histogram.get_percentile_to_value_dict(res.keys()) == res
```
I think that might work better for go as well?
Normally using float as a dict key is not always recommended because the float range fo values is not always mapping one to one to the float representation but here we are talking about a relatively limited set of values between 0 and 100.

**Comment by ahothan** [comment]
> With regards to the added tests/benchmarks, and to benchmark with a data distribution that makes sense I've added gonum as a test dependency. That raised the issue of testing with EOLife versions. If you guys agree I've kept only go 1.14 and go1.15 as the tested versions given all others have EOL. wdyt @giltene and @ahothan ?

I think that is fine.

**Comment by filipecosta90** [comment]
> Although the distinction between "percentile" and "quantile" is not always clear cut, I think "percentile" is more accurate term because "quantile" is a more generic term and the api clearly cannot take anything else than percentiles (e.g. quartiles and such).
Perhaps we should leave the exiting quantile api and add 2 extra apis that use "percentile".

@ahothan @giltene Should we add `ValueAtPercentile()` and `ValueAtPercentiles()`?

> As for the signature of the new go api, I find it a bit annoying to use array indexing to access the percentile values as you need to remember to which index each percentile corresponds.

Will do the changes @ahothan  :+1: :)

**Comment by ahothan** [comment]
> 
> @ahothan @giltene Should we add `ValueAtPercentile()` and `ValueAtPercentiles()`?

+1

> 
> > As for the signature of the new go api, I find it a bit annoying to use array indexing to access the percentile values as you need to remember to which index each percentile corresponds.
> 
> Will do the changes @ahothan 👍 :)

BTW, to relax a bit on the user side and align with python api, it might be better to remove the requirement to pass sorted list of percentiles and support any order (just need to add a sort at start of function) and adjust the unit test accordingly.

**Comment by filipecosta90** [comment]
> > @ahothan @giltene Should we add `ValueAtPercentile()` and `ValueAtPercentiles()`?
> 
> +1
> 
> > > As for the signature of the new go api, I find it a bit annoying to use array indexing to access the percentile values as you need to remember to which index each percentile corresponds.
> > 
> > 
> > Will do the changes @ahothan +1 :)
> 
> BTW, to relax a bit on the user side and align with python api, it might be better to remove the requirement to pass sorted list of percentiles and support any order (just need to add a sort at start of function) and adjust the unit test accordingly.

@giltene and @ahothan I've followed the last reviews and removed the requirement for sorted inputs on ValueAtPercentiles() and added ValueAtPercentile() API. 
I believe we're good to go. WDYT?

**Comment by filipecosta90** [comment]
> The new multi-perecentile api makes sense, and we should probabky consider a similar thing in the other language implementations.

PS: @giltene @ahothan working on the C version variation. Tomorrow should have updated benchmark numbers for that implementation as well :) 
https://github.com/RedisBloom/HdrHistogram_c/commit/cf8c0b47b94ff65e7948a56ee827eaf195e7464d

**Comment by filipecosta90** [comment]
while working on the C version I've noticed we have a bug on this implementation that I need to fix. We can have multiple percentiles being calculated using the same counts position. Will fix it

**Comment by filipecosta90** [comment]
> while working on the C version I've noticed we have a bug on this implementation that I need to fix. We can have multiple percentiles being calculated using the same counts position. Will fix it

@giltene @ahothan with regards to the above issue, fixed in https://github.com/HdrHistogram/hdrhistogram-go/pull/44/commits/1ebc3c3fd53ba0b409d4995a4db7656f74f405e7

IMHO ready for review :)

**Comment by filipecosta90** [comment]
> add out of range percentiles



> also check the lower bound (check against negative numbers)

@ahothan included the requested tests.

**Pull request merged**
